if (!requireNamespace("BiocManager", quietly = TRUE))
  +     install.packages("BiocManager")
if (!requireNamespace("treeio", quietly = T))
  + BiocManager::install("treeio")
if (!requireNamespace("ggtree", quietly = T))
  + install.packages("ggtree")
if (!requireNamespace("phytools", quietly = T))
  + BiocManager::install("phytools")
if (!requireNamespace("dplyr", quietly = T))
  + install.packages("dplyr")
library(ape)
library(treeio)
library(ggtree)
library(phytools)
library(dplyr)
tree_vis<-function(treefile=dir(pattern = '*fa.treefile'),taxfile=dir(pattern='parsed*') pngfile='tree_plot.png'){
  tree <- read.tree(treefile)
  tree_r<- midpoint.root(tree)
  edge<-data.frame(tree_r$edge, edge_num=1:nrow(tree_r$edge))
  colnames(edge)<-c('parent', 'node', 'edge_num')
  taxonomy<-read.table(taxfile, sep='|', header=F)
  colnames(taxonomy)<-c('Accession', 'Protein', 'Lineage', 'Ecology')
  taxonomy2<-filter(taxonomy, Accession %in% tree_r$tip.label)
  tree_r$tip.label<-taxonomy2$Ecology
  #Load unique parents numbers into group:
  group<-groupClade(tree_r, .node=c(min(edge$parent):max(edge$parent)))
  png(filename=pngfile)
  ggtree(group, aes(color=group), rooted=TRUE)+geom_tiplab(size=1.8)+theme(legend.position='none')
  dev.off()
}
tree_vis()
